### ISSUE TITLE
Эталонное НЕНУЖНО

### ISSUE THREAD

**Issue by DosWorld** [symasm/ru#1]
Поздравляю, Вы изобрели https://c--sphinx.narod.ru/ , офф исходники https://github.com/jossk/c--sphinx

**Comment by alextretyak** [comment]
Поздравляю. Вы вообще не поняли, что такое симкод.

Давайте разберём по пунктам информацию из [README](https://github.com/jossk/c--sphinx/blob/master/README) по вашей ссылке.
(На странице <https://c--sphinx.narod.ru/about.htm> приводится перевод на русский, который не совсем точный, поэтому комментировать я буду непосредственно оригинал на английском.)

> C-- is a programming language occupying an intermediate position between Assembler and C.

Симкод не занимает никакого промежуточного положения.
Симкод — это в чистом виде язык ассемблера. Сишная в нём только форма записи.

> It is ideally suited for writing small programs, TSRs, drivers, or interrupt handlers.

Симкод предназначен **не для написания**, а **для чтения** машинного кода, сгенерированного компиляторами языков высокого уровня (C++, Rust) и не очень высокого (хоть этот же C--).

> In order to work with C--  you should know Assembler and C.

Для работы с симкодом не нужно знать ни ассемблер, ни Си.

**Comment by DosWorld** [comment]
-
